import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

import Hexagons from "../components/Hegagons";

import { CountdownCircleTimer } from "react-countdown-circle-timer";

import { useState } from "react";

export default function Home() {
  const [showWindow, setShowWindow] = useState(null);
  const [playing, setPlaying] = useState(false);

  const [top, setTop] = useState(0);
  const [left, setLeft] = useState(0);

  const [key, setKey] = useState(0);


  // 0 - white
  // 1 - orange
  // 2 - blue
  // 3 - black
  const [colors, setColor] = useState([
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0,
  ]);
  const [letters, setLetters] = useState([
    "AZK",
    "BK",
    "C",
    "D",
    "EŠ",
    "F",
    "G",
    "H",
    "ChCh",
    "I",
    "JČ",
    "K",
    "LLL",
    "M",
    "NM",
    "O",
    "P",
    "QT",
    "R",
    "S",
    "Š",
    "T",
    "U",
    "VMK",
    "W",
    "X",
    "Y",
    "Z",
  ]);

  const handleClick = (id, top, left) => {
      setTop(top);
      setLeft(left);
      setShowWindow(id);

      setKey(prevKey => prevKey + 1);
      setPlaying(false);
  };

  const handleClose = () => {
    setShowWindow(null);
    setPlaying(false);
  };

  const handleWinner = (color) => {
    let newColors = [...colors];
    if (color === "orange") {
      newColors[showWindow - 1] = 1;
    } else if (color === "blue") {
      newColors[showWindow - 1] = 2;
    } else if (color === "black") {
      newColors[showWindow - 1] = 3;
    }
    setColor(newColors);

    setShowWindow(null);
    setPlaying(false);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        {showWindow !== null ? (
          <>
            <div
              className={styles.questionClose}
              onClick={() => handleClose()}
            ></div>

            <div
              className={styles.countdownContainer}
            >
              <div
                className={styles.countdownHexagon}
                style={{ top: top, left: left }}
                onClick={() => setPlaying(true)}

              >
                <CountdownCircleTimer
                  key={key}
                  isPlaying={playing}
                  duration={10}
                  colors={["#000", "#37af00",  "#ff1111", "#ff1111"]}
                  size={60}
                  colorsTime={[10, 6, 2, 0]}
                  strokeWidth={5}
                ></CountdownCircleTimer>
                <div className={styles.questionLetter}>
                  {letters[showWindow - 1]}
                </div>
              </div>
            </div>

            <div className={styles.questionWinner}>
              <div
                className={styles.questionWinnerBlue}
                onClick={() => handleWinner("blue")}
              ></div>
              <div
                className={styles.questionWinnerBlack}
                onClick={() => handleWinner("black")}
              ></div>
              <div
                className={styles.questionWinnerOrange}
                onClick={() => handleWinner("orange")}
              ></div>
            </div>
          </>
        ) : (
          ""
        )}
        <Hexagons handleClick={handleClick} colors={colors} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
